### ISSUE TITLE
Will this work with Doctrine?

### ISSUE THREAD

**Issue by l0c0luke** [CodeSleeve/stapler#148]
I know you mention Eloquent, but was just curious if this has already been done with Doctrine?

**Comment by tabennett** [comment]
In theory, Yes. You would just need to write a trait for your Doctrine entities so that they could implement the Staplerable Interface (probably using Lifecycle callbacks, etc). I haven't written this due to the fact that I haven't had a need for it (yet). If you want to take a stab at implementing it, be my guest. I'll help where I can.
